### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by owen-soak** [knex/documentation#410]
Apologies if this isn't the correct place for this, but the new documentation is immediately more difficult to use at least in this example (it is how i personally use knex most often). 

So previously I could search the documentation for a method/method and immediately find the method in the sidebar on the left was always open, the new documentation menu appears closed so you have to click through to see the sections associated,

Any chance we could have the menu fully open on all pages? And maybe even the homepage Was handy seeing them all in one blast :D

**Comment by kibertoad** [comment]
@stafyniaksacha

**Comment by OlivierCavadenti** [comment]
That seems that changelog is outdated (last version = 1.0.7).
Anyway the new documentation is pretty neat !

**Comment by stafyniaksacha** [comment]
Hello @owen-soak ! Thanks for your feedback! It's really important to improve usage in addition to readability.

I just fixed the search with algolia. The pages were redirected to 404.
You can hit `ctrl+k` to search on the whole site (instead of `ctrl+f`)
We can remove the default query `Installation` to nothing, so you will see your last search? Also, what do you think about the search with algolia? (we can configure its index to be more pertinent)

Also, when you are on a specific section, like http://knexjs.org/guide/query-builder.html, you still be able to use plain text search with `ctrl+f`

Maybe we can find a way to open all collapsed menu items too?

**Comment by owen-soak** [comment]
Thanks for responding, the `ctrl + k `is very helpful and seems like it replicates well how I used to search (the document), this search seems very quick but I really only search for method names so don't think I'm stretching the complexities of the search index you have set up.
