### ISSUE TITLE
toSQL doesn't handle parameters correctly for postgres

### ISSUE THREAD

**Issue by jimsimon** [knex/documentation#63]
When using knex as purely a query builder (not specifying connection details), the output of toSQL has `?`'s in it instead of `$1`, `$2`, etc.  The `?` placeholder is bot valid for postgres.  This doesn't appear to be an issue when specifying connection details.

**Comment by elhigu** [comment]
Knex has always used `?`to mark placeholders in every dialect, when toSQL() is called. Passing connection details has nothing to do with that functionality. 

In knex 0.14 there will be method `toSQL().toNative()` which will give you sql which uses dialect specific bindings.

**Comment by jimsimon** [comment]
Well, when you pass connection details there's code that is executed that sets the Postgres specific placeholders.  It seems odd that I toSQL produces SQL that can't be executed against Postgres when setting the dialect to `pg`.

**Comment by jimsimon** [comment]
Maybe it makes sense to remove the last sentence from that part of the docs?

**Comment by elhigu** [comment]
That part is outdated in other way too, since it is not possible to create knex instance without client anymore. There is another doc issue about removing the whole thing.

`toString()` and `toSQL()` returns exactly the same thing regardless if the `connection`attribute are passed to configuration. But `toSQL()` output is not exactly the same thing that is passed to underlying DB driver when knex internally executes the query.

So the only difference is that if you pass also connection details `knex` can execute queries.

And yeah it hasn't really been possible to use knex nicely as a plain query builder so far. Feature that outputs real dialect specific runnable SQL with bindings is coming in 0.14.

**Comment by jimsimon** [comment]
Sounds good, I'll wait patiently for 0.14 :). Thanks!
